// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmetoqajlpzpbubjequt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZXRvcWFqbHB6cGJ1YmplcXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MDE5MjQsImV4cCI6MjA1MDI3NzkyNH0.c7DY8Pbw1MM6fnDSCdfAx1VfvWTAiQunBu8jNBZsc44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);